#!/usr/bin/env php
<?php

$paths = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
];

foreach ($paths as $file) {
    if (file_exists($file)) {
        define('TESTING_COMPOSER_INSTALL', $file);

        break;
    }
}

require_once TESTING_COMPOSER_INSTALL;

use LaraPKG\Testing\Console\Loader;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Console\Application;
use Illuminate\Support\Str;

$container = new Container;
$events = new Dispatcher($container);

$artisan = new Application($container, $events, 'Version 1');
$artisan->setName("Becommerce Testing");

$loader = new Loader($container->make(Str::class));
$loader->loadCommands($artisan);

$code = $artisan->run();

exit($code);
